### ISSUE TITLE
emptyView not shows

### ISSUE THREAD

**Issue by igorka48** [Omega-R/OmegaRecyclerView#108]
emptyView property doesn't work
I tried add emptyView into BaseListAdapter Example, but nothing was shown

`    <com.omega_r.libs.omegarecyclerview.OmegaRecyclerView
        android:id="@+id/recyclerview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:emptyView="@layout/view_no_items"
        app:dividerShow="middle"
        app:dividerHeight="1dp"
        app:divider="@color/colorPrimary"
        app:dividerPaddingStart="24dp"
        app:dividerPaddingEnd="24dp"/>`

Need i do something extra? Or this will be enough? 

There is no valid sample with emptyView in repository.
Can you provide valid sample?

**Comment by R12rus** [comment]
Hi @igorka48. Please use view id instead of app:emptyView="@layout/view_no_items".

```
    <?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".ListAdapterExample.ListAdapterActivity">

    <com.omega_r.libs.omegarecyclerview.OmegaRecyclerView
        android:id="@+id/recyclerview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:dividerShow="middle"
        app:dividerHeight="1dp"
        app:divider="@color/colorPrimary"
        app:dividerPaddingStart="24dp"
        app:dividerPaddingEnd="24dp"
        app:emptyView="@id/layout_empty"/>

    <include layout="@layout/include_empty"/>

</FrameLayout>
```

And include layout looks like:

```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/layout_empty"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/black"/>
```
