### ISSUE TITLE
How can I update only child in expandable recyclerview?

### ISSUE THREAD

**Issue by cashchii** [Omega-R/OmegaRecyclerView#127]
I have some question while using this library.
I wonder if we can update only child data in expandable recyclerview?
Because I haven't see issues about this and also in doc didn't says about it.
Thank you for your worked hard on this library. It's so awesome :)

**Comment by scrinoman** [comment]
Hi, @cashchii !
I'm afraid that it is not possible in current version, so we decided to add this one in our feature-plan list. We will notify you as soon as this feature will be released :)

**Comment by scrinoman** [comment]
It is now possible to update only one child using 
`public void notifyChildChanged(CH child)`
 
Check it out in release 1.9.8
