### ISSUE TITLE
Kotlin examples

### ISSUE THREAD

**Issue by jakkie** [Omega-R/OmegaRecyclerView#79]
Do you have any kotlin examples? I would like to implement the sticky header

**Comment by anton-knyazev** [comment]
Hi, jakkie!

To add sticky header into project you need implements StickyHeaderAdapter in adapters class

Kotlin exemple:
```kotlin
class ExampleStickyHeaderAdapter: OmegaRecyclerView.Adapter<ExampleStickyHeaderAdapter.ViewHolder>(), 
StickyHeaderAdapter<ExampleStickyHeaderAdapter.HeaderHolder> {

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ExampleStickyHeaderAdapter.ViewHolder {
        return ViewHolder(parent)
    }

    override fun onBindViewHolder(holder: ExampleStickyHeaderAdapter.ViewHolder, position: Int) {
        holder.item.text = "Item $position"
    }

    override fun getItemCount(): Int {
        return 54
    }

    override fun getHeaderId(position: Int): Long {
        return position.toLong() / 6
    }

    override fun onCreateHeaderViewHolder(parent: ViewGroup): HeaderHolder {
        return HeaderHolder(parent)
    }

    override fun onBindHeaderViewHolder(viewHolder: HeaderHolder, position: Int) {
        viewHolder.header.text = "Header " + getHeaderId(position)
    }

    inner class ViewHolder(parent: ViewGroup) : OmegaRecyclerView.ViewHolder(parent, R.layout.item_test) {
        var item = itemView as TextView

    }

    inner class HeaderHolder(parent: ViewGroup) : OmegaRecyclerView.ViewHolder(parent, R.layout.sticky_header_test) {
        var header = itemView as TextView
    }
}

```

**Comment by jakkie** [comment]
I successfully implemented you  recycler view but cant seem to get it working with my data model. How would you implement a model say like this for example where each section doesn't have the same row items?
[
[type: section, description: fruits],
[type: row, description: apple],
[type: row, description: orange],
[type: section, description: sweets],
[type: row, description: lolly pops],
[type: row, description: oreos],
[type: row, description: kit kat],
[type: section, description: tasks],
[type: row, description: buy things]
]

Sorry for this stupid question as Im new to android development.
