### ISSUE TITLE
Failed to resolve: com.github.Omega-R:OmegaRecyclerView:1.7.5

### ISSUE THREAD

**Issue by MitchDroid** [Omega-R/OmegaRecyclerView#87]
Hi @anton-knyazev , Could you help me with this compile issue please?

I am following the configurations steps but when I try tu sync, I am getting that issue.
this is the way that I adding the dependency:
 implementation 'com.github.Omega-R:OmegaRecyclerView:1.7.5@aar'

Cheer

**Comment by anton-knyazev** [comment]
Hi @MitchDroid, try using the following:
`implementation 'com.github.Omega-R:OmegaRecyclerView:1.7.6@aar'`

Cheer

**Comment by MitchDroid** [comment]
Hi @anton-knyazev , thanks for your response, I am getting the same error yet! :(

Cheers

**Comment by anton-knyazev** [comment]
@MitchDroid, try to check:
1) gradle offline
2) jitpack

**Comment by MitchDroid** [comment]
Fixed!!...... thanks
