### ISSUE TITLE
Disable one side swipe?

### ISSUE THREAD

**Issue by pranavlathigara** [Omega-R/OmegaRecyclerView#88]
I have requirement that ,
I want to disable right swipe menu on specific position so is that possible with this library?

Thank you the library

**Comment by anton-knyazev** [comment]
HI, @pranavlathigara! 
I did not understand what you want, could you give an example in the form of a picture

**Comment by pranavlathigara** [comment]
i have implemented left and right side swipe menu in my application,
and i have requirement that is i want to disable right swipe menu on certain position e.g Index 3

**Comment by R12rus** [comment]
Hi, @pranavlathigara.
Unfortunately it's not possible. You can block swipe only for both sides.
We will work on this in future.

**Comment by pranavlathigara** [comment]
oh OK no problem 
i have implement this as remove view form parent on specific position and it will work 
` ViewGroup rightParent = (ViewGroup) tvShowRecipe.getParent();
                if (rightParent != null) {
                    rightParent.removeView(textView);
                }`

**Comment by R12rus** [comment]
Hi, @pranavlathigara 
Check new version 1.7.7.
Now you can use three methods:
setRightSwipeEnable(true/false)
setLeftSwipeEnable(true/false)
setSwipeEnable(true/false)
